import httpx

# ... existing code ...

def get_replicate_client():
    # ... existing code ...
    client = httpx.Client(base_url="https://api.replicate.ai")
    # ... existing code ...

# ... existing code ...