// ...

// Assuming these are the lines causing the errors (58,31) and (63,79)
const headerValue = response.headers['content-disposition'] as string;
// ...
if (headerValue.includes('filename=')) {
    // ...
}

// Alternatively, you can use the String() function to coerce the value to a string
const headerValue = String(response.headers['content-disposition']);
// ...
if (typeof headerValue === 'string' && headerValue.includes('filename=')) {
    // ...
}